#!/usr/bin/env python3
"""
Verify Dart-generated signature using Python satori-lite code.

This script tests cross-language compatibility between:
- Dart SignMessage implementation (Magic app)
- Python python-evrmorelib verification (satori-lite)
"""

import sys
import os

# Add lib-lite to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lib-lite'))

from satorilib.wallet.evrmore.verify import verify

# Test vectors - these will be filled in from Dart output
# Or we can use known test vectors

def test_dart_signature():
    """Test signature generated by Dart code"""
    print("=== PYTHON SIGNATURE VERIFICATION ===\n")

    # Test message (must match Dart exactly)
    message = "test message 123"

    # These values will come from Dart script output
    # For now, using placeholders - we'll fill these in after running Dart
    dart_pubkey = None  # Will be 66-char hex string
    dart_signature = None  # Will be base64 string

    # Option 1: If we have Dart values, verify them
    if dart_pubkey and dart_signature:
        print(f"Message: \"{message}\"")
        print(f"Pubkey: {dart_pubkey}")
        print(f"Signature: {dart_signature}")
        print()

        try:
            is_valid = verify(
                message=message,
                signature=dart_signature.encode() if isinstance(dart_signature, str) else dart_signature,
                publicKey=dart_pubkey,
            )

            if is_valid:
                print("✅ SUCCESS: Dart signature verified by Python!")
                print("Cross-language compatibility confirmed!")
                return True
            else:
                print("❌ FAILED: Signature verification failed")
                return False

        except Exception as e:
            print(f"❌ ERROR during verification: {e}")
            import traceback
            traceback.print_exc()
            return False

    else:
        print("⚠️  No Dart signature provided yet.")
        print("Run the Dart script first to generate a signature, then update this script.\n")
        return test_python_to_python()


def test_python_to_python():
    """Generate and verify signature in Python (sanity check)"""
    print("=== PYTHON SELF-TEST (Sanity Check) ===\n")

    from satorilib.wallet.evrmore import Identity
    from satorilib.wallet.evrmore.sign import signMessage
    from evrmore.wallet import CEvrmoreSecret
    from evrmore.signmessage import EvrmoreMessage

    # Test WIF key
    test_wif = 'cW2YkiSzKVcG3VVKKBhVpAJFKdigjfXgDE2fxkk6YJW9Q9qoRUSc'
    message = "test message 123"

    try:
        # Create key from WIF
        key = CEvrmoreSecret(test_wif)

        # Get pubkey
        pubkey_bytes = key.pub
        pubkey_hex = pubkey_bytes.hex()

        # Sign message
        sig_bytes = signMessage(key, message)
        sig_base64 = sig_bytes.decode('ascii')

        print(f"WIF: {test_wif}")
        print(f"Pubkey (hex): {pubkey_hex}")
        print(f"Message: \"{message}\"")
        print(f"Signature (base64): {sig_base64}")
        print()

        # Verify signature
        is_valid = verify(
            message=message,
            signature=sig_bytes,
            publicKey=pubkey_hex,
        )

        if is_valid:
            print("✅ Python self-test PASSED")
            print("\nExpected Dart output:")
            print(f"  Pubkey: {pubkey_hex}")
            print(f"  Signature: {sig_base64}")
            print("\nIf Dart produces the same values, compatibility is confirmed!")
            return True
        else:
            print("❌ Python self-test FAILED")
            return False

    except Exception as e:
        print(f"❌ ERROR in Python self-test: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == '__main__':
    print("Cross-Language Signature Verification Test")
    print("=" * 60)
    print()

    success = test_dart_signature()

    print()
    print("=" * 60)

    sys.exit(0 if success else 1)
