-- =============================================================================
-- Migration: Create streams metadata table for satori-lite client
-- Date: 2026-01-03
-- Description: Creates streams table to store metadata about data streams
--              that the client is tracking and storing in individual tables
-- =============================================================================

-- Note: This is SQLite syntax (client uses SQLite, not PostgreSQL)

BEGIN TRANSACTION;

-- =============================================================================
-- Create streams metadata table
-- =============================================================================

CREATE TABLE IF NOT EXISTS streams (
    -- Local primary key
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Stream ID from central server
    server_stream_id INTEGER,

    -- Stream UUID from server - used as table name for stream data
    -- This UUID is generated by the server and sent in the observation response
    uuid TEXT UNIQUE NOT NULL,

    -- Human-readable stream name (e.g., "bitcoin", "ethereum")
    name TEXT,

    -- Author pubkey - wallet_pubkey of peer allowed to publish on this stream
    author TEXT,

    -- Optional secondary identifier
    secondary TEXT,

    -- Optional target field (from server)
    target TEXT,

    -- Optional metadata field
    meta TEXT,

    -- Optional description
    description TEXT,

    -- Last time we synced metadata from server
    last_synced TIMESTAMP,

    -- When this stream was first registered locally
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_streams_uuid ON streams(uuid);
CREATE INDEX IF NOT EXISTS idx_streams_name ON streams(name);
CREATE INDEX IF NOT EXISTS idx_streams_server_id ON streams(server_stream_id);

-- =============================================================================
-- Verification
-- =============================================================================

-- Verify table was created
SELECT name, sql FROM sqlite_master
WHERE type='table' AND name='streams';

-- Verify indexes were created
SELECT name FROM sqlite_master
WHERE type='index' AND tbl_name='streams';

COMMIT;

-- =============================================================================
-- Success message
-- =============================================================================

-- SQLite doesn't support \echo, but you can verify by querying:
-- SELECT 'Migration completed successfully' AS status;
